/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DirectusFiles {
  charset: string | null;
  created_on: Generated<Timestamp>;
  description: string | null;
  duration: number | null;
  embed: string | null;
  filename_disk: string | null;
  filename_download: string;
  filesize: Int8 | null;
  focal_point_x: number | null;
  focal_point_y: number | null;
  folder: string | null;
  height: number | null;
  id: string;
  location: string | null;
  metadata: Json | null;
  modified_by: string | null;
  modified_on: Generated<Timestamp>;
  storage: string;
  tags: string | null;
  title: string | null;
  tus_data: Json | null;
  tus_id: string | null;
  type: string | null;
  uploaded_by: string | null;
  uploaded_on: Timestamp | null;
  width: number | null;
}

export interface DirectusFolders {
  id: string;
  name: string;
  parent: string | null;
}

export interface FormTypes {
  date_created: Timestamp | null;
  date_updated: Timestamp | null;
  form_code: string;
  form_description: string | null;
  form_name: string;
  id: string;
  sort: number | null;
  status: Generated<string>;
  user_created: string | null;
  user_updated: string | null;
}

export interface FormUpdates {
  date_created: Timestamp | null;
  date_effective: Timestamp | null;
  date_updated: Timestamp | null;
  id: string;
  sort: number | null;
  status: Generated<string>;
  update_content: string | null;
  update_description: string | null;
  update_tags: Json | null;
  update_title: string | null;
  user_created: string | null;
  user_updated: string | null;
}

export interface DB {
  directus_files: DirectusFiles;
  directus_folders: DirectusFolders;
  form_types: FormTypes;
  form_updates: FormUpdates;
}
